### ISSUE TITLE
Searchable descriptions

### ISSUE THREAD

**Issue by CitrusWire** [Calinou/godot-asset-library-laravel#244]
Assuming my guess as to what this contains is correct:
https://github.com/Calinou/godot-asset-library-laravel/blob/fb3ccd9f69674e94ff8553be8aa46d0a36dc287f/app/Asset.php

the search won't be searching `description ` field. Probably also worth throwing in `category` (I know it'll probably be searchable separately, but including it in free-text search is usually useful)

````
    /**
     * The columns that can be searched for using the search string syntax.
     *
     * @var array
     * @see https://github.com/lorisleiva/laravel-search-string#configuring-columns
     */
    protected $searchStringColumns = [
        'title' => ['searchable' => true],
        'blurb' => ['searchable' => true],
        'cost' => 'license',
        'support_level_id',
        'tags' => ['searchable' => true],
        'created_at',
        'modify_date' => 'updated_at',
        'score',
    ];

```

I'd also probably expect that `support_level_id` to actually be `support_level`, and the `cost` to be `license` - but I'm only basing this on that one file.

**Comment by Calinou** [comment]
Sorry, but I don't intend to make descriptions searchable. This is because it would make search much less useful by returning less relevant results.

Searching in the title, blurb and tags is plenty to get relevant results. If it's not the case, it's up to the asset author to improve their SEO :slightly_smiling_face:
